name: Build

on:
  push:
    branches:
      - yc-hacking
    tags:
      - v*
  pull_request:
    branches:
      - yc-hacking
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        name: Build Binary
        if: contains(github.ref, '-snapshot')
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu x86_64-unknown-linux-musl
                      main_target: x86_64-unknown-linux-gnu
                      artifact_name: neocmakelsp
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}
            - name: Install gcc-musl
              if: ${{ matrix.os  == 'ubuntu-latest' }}
              run: sudo apt install -y musl-tools
            - name: Build musl
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: cargo build --target x86_64-unknown-linux-musl --verbose --release
            - name: Upload artifacts musl
              if: ${{ matrix.os == 'ubuntu-latest' }}
              uses: actions/upload-artifact@v4
              with:
                  path: target/x86_64-unknown-linux-musl/release/${{ matrix.artifact_name }}
                  name: "x86_64-unknown-linux-musl"
    release:
        permissions:
            contents: write
        if: contains(github.ref, '-snapshot')
        needs:
            - build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
            - name: Show files
              run: |
                  pwd
                  find
            - name: Copy files
              run: |
                  mkdir out
                  mv x86_64-unknown-linux-musl/neocmakelsp out/neocmakelsp-x86_64-unknown-linux-musl
                  cd out
                  sha256sum * > sha256sum
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: out/*
                  draft: true
